### ISSUE TITLE
Best name for ParametricTypeImplIO

### ISSUE THREAD

**Issue by chrisklus** [phetsims/tandem#104]
In https://github.com/phetsims/tandem/issues/101, we chose to rename ParametricTypeIO to ParametricTypeImplIO, since that is more correct with its purpose. But @samreid and I think we might be able to think of a name we like better. This became important because we noticed that ParametricTypeImplIO is leaking into the API and all of the phet-io types files.

**Comment by pixelzoom** [comment]
I don't see `ParametricTypeImplIO` in master, and I have no idea what an "ImplIO" is.  So the only feedback I can provide is that "ImplIO" violates this item in the code review checklist:

> - [ ] Names (types, variables, properties, functions,...) should be sufficiently descriptive and specific, and should avoid non-standard abbreviations. For example: ...

**Comment by pixelzoom** [comment]
8/29/19 dev meeting:
`ParametricTypeImplIO` is an inner type of `ParametricTypeIO`

**Comment by zepumph** [comment]
I think this decision was settled, and the implementation will be done over in https://github.com/phetsims/tandem/issues/101. I'm ready to close this. @chrisklus what do you think?

**Comment by pixelzoom** [comment]
What was the decision? Please don't make me go dig for it.

**Comment by zepumph** [comment]
Since this discussion aboce, `ParametricTypeIO.js` was deleted, see https://github.com/phetsims/tandem/issues/100. Sorry that I was not explicit above. 

To some up this issue currently, I would say that the "Impl" piece of these names stands for Implementation, and they are private to their individual parametric type files. This naming is an unfortunate byproduct of creating our own custom parametric Types in javascript. Likely we could name them better.

Currently we have the following terms as they pertain to Property:

* `PropertyIO`, which is not an IOType, but rather a function that takes the parameter IO type and returns a created IO Type, like `PropertyIO( BooleanIO )`. We decided that the comfortable client api was worth the weirdness in naming.
* Inside `PropertyIO.js`, the function `PropertyIO` takes these parameters, and then constructs the actual IO Type, this local variable that is returned by the PropertyIO function is named `PropertyIOImpl`. 

I don't think there is anything left for this issue except to clarify understanding @pixelzoom. Perhaps we should make a new issue to address renaming these local `*Impl` vars?

**Comment by zepumph** [comment]
After reading https://github.com/phetsims/tandem/issues/101#issuecomment-525823807, perhaps this is the correct place to discuss renaming all of these "Impl" variables.

**Comment by samreid** [comment]
What if we name the outer types like `PropertyIOT( NumberIO)` and the inner types as `PropertyIO( NumberIO )`.  The `T` stands for `Template` and is used for the outer type template.  The inner type is named as we want it to appear in the client-facing API file.

**Comment by pixelzoom** [comment]
Sounds like @samreid has some suggestions that may not have been considered, and this issue may not be ready to close after all.
