### ISSUE TITLE
How to deal with Tandem.required in the options?

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#122]
There is a topic we didn't cover in https://github.com/phetsims/phet-info/issues/117 which is about dealing with `Tandem.required`.  The current pattern is to specify:

```js
   options = merge( {
      // ... other options

      // PhET-iO
      tandem: Tandem.required
    }, options );
```

This is kind of odd because the tandem isn't actually required in "phet" brand, so it is listed in the options.  I'm not sure whether this was by design or we just ended up here haphazardly, and I'm not sure whether it needs discussion or not.

@zepumph @pixelzoom @Denz1994 what do you think?

**Comment by pixelzoom** [comment]
I'm happy to overlook this wart, and the current approach seems to be working fine.

**Comment by Denz1994** [comment]
I agree with @pixelzoom for this reason. `Tandem.required` is deriving its value from an optional field in an options object. So that would make the `tandem` field in @samreid [comment](https://github.com/phetsims/tandem/issues/122#issue-517373145) above also an optional field. 

If Tandem.js options object doesn't have a required field for `required` then its use case somewhere else shouldn't either. I'm referencing the below snippet from Tandem.js.

``` 
 options = merge( {

        // required === false means it is an optional tandem
        required: true,

        // if the tandem is required but not supplied, an error will be thrown.
        supplied: true
      }, options );

      // @private
      this.required = options.required;
```

**Comment by samreid** [comment]
Sounds good, thanks!  Closing.
