### ISSUE TITLE
Should we use string concatenation or whole terms for tandem components?

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#128]
See https://github.com/phetsims/scenery-phet/issues/540#issuecomment-553643702

This issue is to discuss and decide between:

```
// concatenation
tandem.createTandem(myModel.tandemName+'ResetButton');

// whole terms
tandem.createTandem(myModel.resetButtonTandemName);
```

Whole terms are more searchable.  Say I am looking to find "particleResetButton", then I would easily be able to track it down.  But whole terms are also more verbose, since we would have to create/store the whole tandems in corresponding places.

Assigning to @zepumph for initial discussion.

**Comment by zepumph** [comment]
In a lot (most) places, it has worked very well to use whole terms. For example. I think using `tandemName` in `RadioButtonGroup.js` makes a bunch of sense. I also agree about "Whole terms are more searchable." In general we should try to do that. 

The reason I don't like it in the case of KeyPad.js is because I don't feel like it is adding anything, and it feels very simple to back trace the tandemName to the source. 

`Key.js` already has all the string data that it needs to be a unique key. So adding an additional arg to each instance here in KeyPad.js seems like busy work that isn't helping us.
```
    PositiveIntegerLayout: [
      [ new Key( '7', KeyID.SEVEN ), new Key( '8', KeyID.EIGHT ), new Key( '9', KeyID.NINE ) ],
      [ new Key( '4', KeyID.FOUR ), new Key( '5', KeyID.FIVE ), new Key( '6', KeyID.SIX ) ],
      [ new Key( '1', KeyID.ONE ), new Key( '2', KeyID.TWO ), new Key( '3', KeyID.THREE ) ],
      [ new Key( '0', KeyID.ZERO, { horizontalSpan: 2 } ), new Key( ( new BackspaceIcon( { scale: 1.5 } ) ), KeyID.BACKSPACE ) ]
    ],

```

@samreid I'd be interested in hearing about you case in GAO. As you mentioned in https://github.com/phetsims/scenery-phet/issues/540#issuecomment-553643702, perhaps all those tandemNames are indicative of greater hierarchical problems. Is it possible to set up tandems instead like this?

```
starPlanetScene
starPlanetScene.button
starPlanetScene.resetButton
starPlanetScene.massControlPanel
```

**Comment by samreid** [comment]
I gravitated to string concatenation in Gravity and Orbits and it helped a lot, closing.
