### ISSUE TITLE
Remove PHET_IO_ENABLED from PhetioObject.isPhetioInstrumented()

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#140]
This is creating branching logic between brands, which is not ideal. In places we are trying to do less work in phet brand, then we should be testing against `Tandem.PHET_IO_ENABLED`.

**Comment by zepumph** [comment]
Most of this issue was going through each usage of `isPhetioInstrumented` and determining if there should be an additional check on `Tandem.PHET_IO_ENABLED`. Here are my thoughts as it pertains to a @samreid as he reviews (please):

* Action.js failed when I removed the `isPhetioInstrumented()` checks on start/end events. I would rather that not be needed. Perhaps we could wrap this in a function like other supported data arguments. What do you think?
* Please take another pass at all usages of `isPhetioInstrumented()` as a way of checking my work, because actually the usages that weren't changed are what need to most reviewing (since they lost the PHET_IO_ENABLED check).
* fuzzing passed for phet-io and phet brands.
* In addition to things "working" should there be consideration about how running some code in phet brand may degrade performance? With that in mind perhaps we should add back the PHET_IO_ENABLED check to Action event functions.

**Comment by samreid** [comment]
In my review, most sites that call `isPhetioInstrumented` (outside of assertions) are safe because the function they call immediately guards on `PHETIO_ENABLED`.  For instance:

```js
this.isPhetioInstrumented() && this.phetioEndEvent();
```

calls 

```js
  phetioEndEvent: function() {
    if ( PHET_IO_ENABLED && this.isPhetioInstrumented() ) {
```

One exception to this is in TinyForwardingProperty:

```js
    else if ( this.targetProperty && this.targetProperty.isPhetioInstrumented() ) {

      // If the Property was already set, now that it is instrumented, add a LinkedElement for it.
      node.updateLinkedElementForProperty( tandemName, null, this.targetProperty );
    }
```

which calls this method:

```js
  updateLinkedElementForProperty( tandemName, oldProperty, newProperty ) {
    assert && assert( oldProperty !== newProperty, 'should not be called on same values' );

    // Only update linked elements if this Node is instrumented for PhET-iO
    if ( this.isPhetioInstrumented() ) {

      oldProperty && oldProperty.isPhetioInstrumented() && this.removeLinkedElements( oldProperty );

      const tandem = this.tandem.createTandem( tandemName );
      if ( newProperty && newProperty.isPhetioInstrumented() && tandem !== newProperty.tandem ) {
        this.addLinkedElement( newProperty, { tandem: tandem } );
      }
    }
  },
```

`addLinkedElement` has a guard, but `removeLinkedElements` does not.  Maybe it doesn't matter because `removeLinkedElements` is graceful anyways.  But do you think this should be symmetric?

`restoreStateForScreen` in ResetAllButton still needs the guard (and it has it).  Everything else looks good.

> * Action.js failed when I removed the `isPhetioInstrumented()` checks on start/end events. I would rather that not be needed. Perhaps we could wrap this in a function like other supported data arguments. What do you think?

Maybe this was implemented in https://github.com/phetsims/axon/commit/e1c69917a9d4150daaa96126ccdf35ea02fff6b5

> In addition to things "working" should there be consideration about how running some code in phet brand may degrade performance? With that in mind perhaps we should add back the PHET_IO_ENABLED check to Action event functions.

The changes we made for https://github.com/phetsims/tandem/issues/224 are more likely to have a measurable impact.  I don't recommend further optimizations.

Summarizing above:
- [ ] Should we make `removeLinkedElements` guard on PHET_IO_ENABLED like `addLinkedElement` does?

**Comment by zepumph** [comment]
As of today, I see that PhetioObject.removeLinkedElements does wrap in a check:

https://github.com/phetsims/tandem/blob/420ccdef0c4b4cd17fe1e1a9d331400ec11de5c0/js/PhetioObject.js#L522-L533



Closing
