### ISSUE TITLE
PhetioObject options should be type validated

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#141]
@pixelzoom just ran into a case where he was accidentally passing through `undefined` as an option and it didn't error loudly, but rather quite a bit later in Studio. This should be an easy fix, and hopefully there aren't too many cases that are doing this silently right now. @chrisklus if you have time for this before me, go for it!

**Comment by pixelzoom** [comment]
More details...

I accidentally set `phetioReadOnly: undefined` for an Action, something like this:

```js
... = new Action( ..., {
  ...
  phetioReadOnly: options.phetioReadOnly
} );
```

`grunt update` succeeded with no errors.  

Studio failed to start with:

> Uncaught Error: Assertion failed: api mismatches present: 2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.

**Comment by chrisklus** [comment]
I added a couple TODOs, and i'm curious about the `phetioIsArchetype` one. @zepumph if you don't mind pairing on this again, I'd like to review together and discuss.

**Comment by zepumph** [comment]
One other thing that I noticed while over in https://github.com/phetsims/tandem/issues/136 is that we should factor out all of the validator options into constant, because even if it is used in a single place, it is still allocated for each PhetioObject that is initialized. That is at least 3 extra objects per PhetioObject instance, and likely worth culling.

**Comment by chrisklus** [comment]
@zepumph helped me look at a few loose ends with validating options and we factored out the rest of the validators as constants. There was some confusion about `phetioIsArchetype` since it was a key in the options `DEFAULTS`, but it wasn't being used since PhetioObject determines the value, so we moved the option declaration needed for `PhetioObject.getMetadata` to use `this.phetioIsArchetype` instead.

Closing.
