### ISSUE TITLE
Improve value and usage of Tandem.PHET_IO_ENABLED

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#153]
At today's meeting, @pixelzoom recommended the following improvements for `Tandem.PHET_IO_ENABLED`.

* He thought we had other cases where another pattern was used to identify phet-io brand.   Perhaps a brand check?  We should look through sites and see if other legacy patterns can be moved to this main pattern.
* Also, we should not set `PHET_IO_ENABLED` solely based on the existence of one global.  It seems better to cross-check this via the brand value, in case somehow a different `phet.phetio` exists in the future for some reason.

Finally, @pixelzoom reported initial confusion because `Tandem.REQUIRED` is of type `Tandem`.  So it seemed reasonable that `Tandem.PHET_IO_ENABLED` might also be a Tandem.  Should this be moved somewhere else or done in a clearer way? 

Would this be better a a chipper global?  Or a Sim constant like `Sim.PHET_IO_ENABLED`?

@pixelzoom any other thoughts on this issue before @zepumph, @chrisklus and I start on it?

**Comment by pixelzoom** [comment]
@samreid This issue overlaps with https://github.com/phetsims/tandem/issues/152.

The only other static Tandem field that's not a Tandem instance is `Tandem.missingTandems`, so that's probably why I thought `Tandem.PHET_IO_ENABLED` was a Tandem instance. 

It does seem like `PHET_IO_ENABLED` belongs elsewhere.  It doesn't seem like this should be Tandem's responsibility.

Making it a global seems a bit odd, since it already relies on global `phet.phetio`.  As noted in https://github.com/phetsims/tandem/issues/152, it should also check brand.

**Comment by samreid** [comment]
Thanks for the remarks @pixelzoom.  @zepumph can you take a look and let me know your recommendations? I'm happy to work on this and equally happy if you want to go for it.

**Comment by zepumph** [comment]
I locally changed the value of PHET_IO_ENABLED to be: `const PHET_IO_ENABLED = _.hasIn( window, 'phet.chipper.brand' ) && phet.chipper.brand === 'phet-io';` and I really like it.

I like factoring out brand checks into a constant like this, and I agree that it makes more sense that `PHET_IO_ENABLED` should run on the brand instead of the presence of the `phet.phetio` global. 

We originally put it in Tandem because it is the lowest level dependency. I thought that it would be nice because we can import Tandem from more other libraries (even scenery). 

I felt like a constant on a module was a bit more robust than a global, because the goal is to have something that we guarantee exists at all usage sites. A global feels like a step in the wrong direction. 

Current usages are in:
* joist
* sun
* axon
* tandem
* sims

tandem is the only repo that has a dependency to all of those repos.

I am not bothered by keeping this as a static on Tandem.js, but some alternatives to compare with could be:

* creating a single file that exports a boolean called `PHET_IO_ENABLED` like `export default _.hasIn( window, 'phet.chipper.brand' ) && phet.chipper.brand === 'phet-io';` (can you even do that?)
* Create `TandemConstants` and usages can be `TandemConstants.PHET_IO_ENABLED`.

To me the `tandem` repo is basically like "publically available phet-io code." With that in mind that repo feels like the appropriate place for this constant. Assigning for feedback and recommendations.

**Comment by pixelzoom** [comment]
Checking `phet.chipper.brand` is much nicer and safer.

`_.hasIn( window, 'phet.chipper.brand' )` seems like it should be an assertion, not part of the definition of `PHET_IO_ENABLED`.   When would it be OK to execute this code without `phet.chipper.brand` defined?

Leaving it as `Tandem.PHET_IO_ENABLED` is fine with me.

**Comment by zepumph** [comment]
>_.hasIn( window, 'phet.chipper.brand' ) seems like it should be an assertion, not part of the definition of PHET_IO_ENABLED. When would it be OK to execute this code without phet.chipper.brand defined?

That is a phetsim-centric view. There could be usages of it in, for example, scenery code that we wouldn't want to fail if running for another scenery usage. I think gracefully stating that a lack of `phet.chipper.brand` means that phet-io is not enabled seems correct to me. It could be good to add an assertion to Sim.js to make sure that phet.chipper.brand exists. What do you think?

**Comment by pixelzoom** [comment]
Re previous comment. That sounds great.

**Comment by zepumph** [comment]
Done above. Closing
