### ISSUE TITLE
why use validator instead of assert in IO type?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#163]
Here's a pattern that I find I'm repeating, because I copied it from other IO types.  In BunnyIO:

```js
static toStateObject( bunny ) {
  validate( bunny, this.validator );
  ...
}

BunnyIO.validator = { isValidValue: value => value instanceof Bunny };
```

Why is this better than just using `assert`, like this?

```js
static toStateObject( bunny ) {
  assert && assert( bunny instanceof Bunny, ... );
  ...
}
```

If I have a choice, I'd prefer to use assertions, because I think they are clearer and more straightforward.

I also don't see `validator` used consistently.  For example, see NumberIO, StringIO, and BooleanIO.

**Comment by zepumph** [comment]
The only difference (besides convention) is that `this.validator` will be the subtypiest validator in the hierarchy. So if there was a `SmartBunnyIO extends BunnyIO` with a validator that had a `valueType: SmartBunny, your first snippet would validate on `SmartBunny` instead of `Bunny`. I'm not quite sure if that is a pro or a con. 

If it is a con, we can still use `validate` by calling `validate( bunny, BunnyIO.validator );`. 


-------------------------------

I understand that the above is slightly off topic. Sorry. I have a preference for validate, because each type already must declare a validator and that avoids likely duplicating that validation code in the `validator` declaration as well as at the top of each static state-related method.

I agree that we should be consistent.

**Comment by pixelzoom** [comment]
This answered my question, thanks.  I'll use `validate` in `toStateObject` and `setValue`. 

FYI, there are plenty of IO Types that do not do that.  If someone wants to create an issue, go for it. 

Closing.
