### ISSUE TITLE
rename ObjectIO.setValue ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#164]
ObjectIO `setValue` could benefit from a more descriptive name, so that it doesn't potentially collide with `setValue` in core types.

For example, this is becoming a common pattern, where the IO type delegates to the core type:

```
// BarGraph.js, core type
class BarGraph { 
  ... 
  // would prefer to call this setValue
  setBarGraphValue( value ) { ... }

  // set state when deserialized, called by BarGraphIO
  setValue( state ) { ... }
}

// BarGraphIO.js, IO type
setValue( graph, value ) {
  graph.setValue( value );
}
```

In this example, `setValue` has another more appropriate meaning in the core type.  Yes we could name `setValue` something else in the core type, but there is advantage/clarity to having the IO type delegate to a method with the same name in the core type.  So in this example, I've had to use `setBarGraphValue` in the core type.

And even without the above pattern, `setValue` is just a vague name. 

Some alternatives:

```js
/**
 * @param {Object} object
 * @param {*} deserializedState - the state information returned by fromStateObject
 */
restoreState( object, deserializedState )
restoreObjectState( object, deserializedState )
mutateState( object, deserializedState ) 
mutateObjectState( object, deserializedState ) 

???
```

**Comment by samreid** [comment]
How about `setStateObject` or `applyState`?

**Comment by zepumph** [comment]
I like `applyState`

**Comment by zepumph** [comment]
I implemented this above. It was a bit finicky since there are so many other usages of `setValue`, but I tested NS and SOM in the state wrapper (the only repos that have IO type setValue functions calling core type `setValue` functions) and all looks good. I liked `applyState`, but don't feel too strongly, mainly I like that now `applyState` is unique to this usage, and if we wanted to rename to something else, we could. Just let me know! @pixelzoom please review, since much of the rename was in Natural Selection.

**Comment by pixelzoom** [comment]
Thanks, looks good to me! Closing.
