### ISSUE TITLE
missing visibility annotations in IO Types

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#178]
Lots of missing visibility annotations in IO Types and IOImpl inner classes.  Recommended to review and fix.

**Comment by pixelzoom** [comment]
I fixed a few in the above commits, but not comprehensive.

**Comment by samreid** [comment]
This will no longer be necessary after we adopt the proposal in https://github.com/phetsims/tandem/issues/211, on hold until that issue is further along.

**Comment by samreid** [comment]
IOType now provides these methods as passed-in options, not as overridden methods that require JSDoc.  As we move methods like `toStateObject` to the core types, we will need to remember to add visibility annotations for those, but I think lint rules will help us remember.  This issue seems ready to close.
