### ISSUE TITLE
TandemSimpleDragHandler should move code to SimpleDragHandler

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#20]
Similar to #18, we should move TandemSimpleDragHandler code to SimpleDragHandler and delete TandemSimpleDragHandler.

**Comment by samreid** [comment]
This will be a significant change, spanning 31 files over 15 repos and nontrivial changes to scenery SimpleDragHandler.  @pixelzoom @jonathanolson @jessegreenberg @jbphet @zepumph brace yourselves.

**Comment by samreid** [comment]
I've implemented it, reviewed it with @zepumph, tested aqua and am thinking this is ready to commit and have Bayes take a closer look.

**Comment by samreid** [comment]
OK commits appear above, I'll leave this issue open and assigned me to check Bayes later on.

**Comment by zepumph** [comment]
@samreid I have been thinking about our decision to emit to the data stream regardless of listener options passed in. 

I think that this is a good choice. I'm seeing that over half of the TandemSimpleDragHandlers (I haven't pulled yet) don'e implement an end event. This would be confusing in the data stream. 

I wanted to spend one more minute thinking about this pattern in regards to the 'drag' listener option. See `shred/js/ElectronCloudView.js`. It doesn't have a 'drag' function, and I'm wondering if having the 'drag' implemented would just 'clog up' the data stream?  

I also see that for types like `forces-and-motion-basics\js\motion\view\ItemNode.js` because it doesn't matter where it is dragged to, just where it is when the drag ends. 

Currently my thoughts are to add the callbacks for dragged emitters back into the conditional for the 'drag' event. What do you think?

**Comment by samreid** [comment]
Both of the examples you provided supply `options.translate`.  In my preceding commit, I moved the drag event to capture both the translate and drag.  It seems best to leave the emitters out of the conditionals.  If we find sites that are using SimpleDragHandler but not doing any drag/translate, then those sites should probably use another type of listener.  And it seems good to catch start+end in the data stream even if the application isn't listening for them.

**Comment by zepumph** [comment]
That sounds great. Good solution.

**Comment by samreid** [comment]
Bayes is tentatively optimistic, closing for now.
