### ISSUE TITLE
Review and Testing for IO Types

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#217]
From https://github.com/phetsims/tandem/issues/211, we have made significant improvements to IO Types, and more changes are planned in issues like:

https://github.com/phetsims/tandem/issues/212
https://github.com/phetsims/phet-io/issues/1709 
https://github.com/phetsims/tandem/issues/213

We want to be confident these changes are all set for production.  Here is the thread from #211:

All TODOs have been addressed or moved to other issues.  The last topic for this issue is how it should be tested.  Some options:

1. (lazy) We alert QA to these changes the next time they are dev or RC testing SHAs that contain these changes.
2. (eager) We create a dedicated version and request up-front testing before other SHAs from master are tested.

The lazy approach may be sufficient in this case, but we have discussed moving toward the eager approach for certain things.  @zepumph and @ariel-phet what do you recommend?

**Comment by samreid** [comment]
@zepumph replied:

I think part of what leans me towards the lazy approach is the difficulty in pin pointing exactly what may have regressed. It may be easier to test eagerly in cases where you can give a runnable to QA and have them go at it. For this issue I would worry about (in no order):

* Type doc changing
* Methods from the wrapper no longer working
* A bug in IOType that causes an API change
* Something that may not have been converted correctly in a specific sim. Hopefully this would get caught on CT, but in the worst case a sim may have a silent state-related bug that.

Nothing above feels like something that QA can tackle efficiently. Likely CT took us 80% there and a code review can take us the rest. What do you think @samreid?

**Comment by samreid** [comment]
@ariel-phet said:

> @samreid @zepumph perhaps a bit of both - considering https://github.com/phetsims/QA/issues/519 is high on the testing list currently (EFAC will come first when the next RC is ready, but GAO is actively being tested) - perhaps after some review, GAO will be ready for its next dev test soon and can include these changes with QA alerted. That should help vet the new approach I would think.

**Comment by samreid** [comment]
Dev testing for Gravity and Orbits completed and no issues related to this were identified.  Based on the preceding 2 comments, can @zepumph review and test the IO type changes (see bullet list 2 comments beforehand)?  Perhaps this should block next PhET-iO RCs.

**Comment by zepumph** [comment]
>Methods from the wrapper no longer working

I feel like studio is testament that this works well.

I looked at the rendered jsdoc, though I don't think that was the point of this review, and found a bug fixed in the above commit.

I noticed https://github.com/phetsims/scenery/issues/1047#issuecomment-716780463.


- [ ] This default is buggy, and doesn't support complex IO Types. It should be rewritten to find the index of the first usage of `IO` and take a substring to that:

```js
      // {string} Documentation that appears in PhET-iO Studio, supports HTML markup.
      documentation: `IO Type for ${ioTypeName.substring( 0, ioTypeName.length - PhetioConstants.IO_TYPE_SUFFIX.length )}`,
```

- [ ] I don't understand the value of wrapForPhetioCommandProcessor as an option/schema in the IO Type interface. I can't think of another type that will use this besides FunctionIO. I feel like we should either (a) get rid of it and hard code logic for functions in the command processor, or (b) rename and make it more explicit what its purpose is, and that it is only useful for functions.

- [ ] This chunk seems unused, half baked, and like it is part of https://github.com/phetsims/phet-io/issues/1657. Can we comment it out with a TODO linked to that issue?

```js
    if ( this.hasOwnProperty( 'api' ) ) {
      assert && assert( this.api instanceof Object, 'Object expected for api' );
      assert && assert( Object.getPrototypeOf( this.api ) === Object.prototype, 'no extra prototype allowed on API object' );
    }
```

I promoted this to a TODO so that it would be dealt with here:
    // TODO: What about EmitterIO<> that has no parameter types?  See https://github.com/phetsims/tandem/issues/217


@samreid please take a look at my suggestions and commit. Everything here seems pretty minor. I'd be fine with you taking off the blocking label, but I think we should try to finish up these loose ends eagerly.

**Comment by samreid** [comment]
Thanks for the feedback.  I addressed them.  I didn't see a robust way to detect FunctionIO in phetioCommandProcessor, so I gave the option a better name.

Should we move 

```js
// TODO: What about EmitterIO<> that has no parameter types? See #217
```

to another issue?  Can you recommend how to process that case?

Please review my commits. Can this issue be closed?

**Comment by zepumph** [comment]
Yes new issue sounds good. Please create.

**Comment by zepumph** [comment]
Everything else looks great.

**Comment by zepumph** [comment]
I created https://github.com/phetsims/tandem/issues/223, I'm going to close this issue.
