### ISSUE TITLE
Different tandem instances can have the same ID

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#25]
There is apparently nothing to prevent tandem ids from being shared between static and non-static. 

 Example, with molecule-polarity loaded in the browser:

```
> var rootTandem = phet.tandem.Tandem.createRootTandem()
> var myTandem = rootTandem.createTandem( 'foo' )
> myTandem.id
"molecule-polarity.foo"
> myTandem.static
false
> var staticTandem = phet.tandem.Tandem.createStaticTandem( 'foo' )
> staticTandem.id
"molecule-polarity.foo"
> staticTandem.static
true
```

This seems like a potential problem.

[NOTE: Example above was edited, I copied some things incorrectly from my console.]

**Comment by pixelzoom** [comment]
I'm guessing that `createGroupTandem` has a similar problem -- i.e., a tandem id used for a group may also be used for a non-group.

**Comment by samreid** [comment]
`createStaticTandem` was eliminated in https://github.com/phetsims/tandem/issues/34

> I'm guessing that `createGroupTandem` has a similar problem -- i.e., a tandem id used for a group may also be used for a non-group.

Yes, the only difference between GroupTandem and Tandem is that GroupTandem adds the following method:

```js
    createNextTandem: function() {
      return new Tandem( this.id + '_' + (this.groupElementIndex++) );
    }
```

Tandem is designed around concatenating strings, hence the following code would not be an error:
```js
var x = tandem.createTandem('hello');
var y = tandem.createTandem('hello');
var z = tandem.createGroupTandem('hello');

var a = z.createNextTandem(); // creates "rootTandem.hello_0"
var b = tandem.createTandem('hello_0'); // creates rootTandem.hello_0
```

On the other hand, `x`, `y` and `z` would all have the same `id`.  Also `a` and `b` have the same `id` and are functionally equivalent.  I'm not sure what alternative implementations we could take.

**Comment by zepumph** [comment]
Good to note that while you can have the same ids, you won't be able to add instances of these same strings without getting an error. 

```js

var x = tandem.createTandem('hello');
var y = tandem.createTandem('hello');
x.createTandem( 'foob').addInstance( oneNode )
y.createTandem( 'foob').addInstance( twoNode ) // <-- will throw error

```

It seems like the main confusion we are trying to avoid would be:

```js

var x = tandem.createTandem('hello');
var y = tandem.createTandem('hello');
x.createTandem( 'foob').addInstance( oneNode ) // creates and adds 'hello.foob'
y.createTandem( 'ar').addInstance( twoNode )  // creates and adds 'hello.ar'
// No errors here captain, but different hellos

```

**Comment by pixelzoom** [comment]
Re this:

```js
var x = tandem.createTandem('hello');
var y = tandem.createTandem('hello');
```

The fact that `x !== y` is problematic, as noted by the example in https://github.com/phetsims/tandem/issues/25#issuecomment-347325181. 

Imo, the second call to `createTandem` should error out -- you can't "create" the same thing twice.  If you really need to get at a tandem that was previously created, then add a `getTandem` call, or (better yet) use assignment.  E.g.:

```js
var x = tandem.createTandem('hello');
var y = tandem.getTandem('hello');
var z = x;
assert && assert( x === y && y === z );
```

**Comment by samreid** [comment]
> then add a getTandem call

Implementing that seems like it would open the door to memory leaks.  I don't understand the problem in https://github.com/phetsims/tandem/issues/25#issuecomment-347325181, why does it matter that they are different hellos?  Currently, only the `tandem.id` is used, which is identical between the two tandems.

**Comment by pixelzoom** [comment]
> Currently, only the tandem.id is used, which is identical between the two tandems.

The key word here is "currently".

**Comment by samreid** [comment]
To future-proof ourselves, we could implement Tandem.equals() and implement it with content-based equality (rather than reference based equality).

**Comment by zepumph** [comment]
It seems like part of the problem here is that our registry exists in phetio, and not in Tandem. If Tandem had a registry of instances, then it would be easy to have `createTandem` validate. I'm not sure I see a large benefit in it though, but more a lateral step.

@samreid could you supply a usage for what you are thinking with `Tandem.equals()`, would that be a static method that takes in two `Tandem`s?

**Comment by samreid** [comment]
I'll rename this issue since static tandems no longer exist.

**Comment by samreid** [comment]
```js
var x = tandem.createTandem('hello');
var y = tandem.createTandem('hello');
```
Doesn't seem problematic to me unless we have code that is comparing tandems for equality, like

```js
myObject1.tandem = tandem.createTandem('hello');
myObject2.tandem = tandem.createTandem('hello');

myObject1.tandem===myObject2.tandem // returns false
myObject1.tandem.equals(myObject2.tandem) // we could implement `Tandem.equals` to get this right
```

I do not yet see the value of doing tandem equality comparisons since it would not be leveraged by our implementation at the moment.

I have been considering Tandem as syntactic sugar for doing string concatenation and it is sufficient for that.  If in the future we start treating Tandems as part of the object structure (not just for the strings), then we will need to investigate this further.  In that case, the main options I see are (a) using a tandem-side registry like @zepumph suggested in https://github.com/phetsims/tandem/issues/25#issuecomment-347614721 or having each Tandem keep track of its own children (would that be a memory/dispose nightmare)?

Unassigning until I hear back from @zepumph and @pixelzoom

**Comment by zepumph** [comment]
@samreid, I think you're right. The main concern here is confusion for developers that are not as used to the system. We should make the purpose of tandems clear in the documentation so that devs understand the original developer's intended usage (sugar for string concat).

I also want to point out that while there could be confusion while developing if someone mistakenly created the same tandem on different instances (especially when these two instances have many children), there is now a lot of design time and "proof reading" of these id's before they end up in any permanent or stable state. 

I recommend no solution but to improve documentation. Currently the only overview about what tandems are is this, as a step in the instrumentation overview in the how to instrument docs:
>Adding unique ids to instances that may appear in the simulation instrumentation (state/data stream/interoperability/etc). This is done by passing tandems throughout the sim instances. A full ID may be something like chargesAndFields.chargesAndFieldsScreen.view.electricPotentialSensorNode.voltageReadout.

**Comment by pixelzoom** [comment]
@samreid said:
> ... I have been considering Tandem as syntactic sugar for doing string concatenation and it is sufficient for that.  ...

That's an internal detail, something that should be encapsulated.  And if you're going to make that assumption throughout client code, then perhaps a full-blown type with instances isn't appropriate for Tandem.

**Comment by pixelzoom** [comment]
@samreid If Tandem is syntactic sugar for string concatenation, why isn't it being used in cases like https://github.com/phetsims/tandem/issues/40#issuecomment-349096675, reproduced here:

```js
// sonificationUISoundsSampled.js
163 var lastIdElement = messageObject.phetioID.split('.').pop();
```

**Comment by pixelzoom** [comment]
And if it's not appropriate to use `Tandem` in cases like the above, consider factoring out the id-related functions so that they can be by both `Tandem` and cases like the above.   With the current approach, you currently have zero encapsulation of the id format.

**Comment by zepumph** [comment]
sonificationUISoundsSampled.js is client wrapper code, so we don't have access to the Tandem instance there. We only have the string literal (phetioID).

**Comment by pixelzoom** [comment]
> sonificationUISoundsSampled.js is client wrapper code, so we don't have access to the Tandem instance there. We only have the string literal (phetioID).

See https://github.com/phetsims/tandem/issues/25#issuecomment-349097990.

**Comment by zepumph** [comment]
We struggle with this, because we don't have a library that that is used on the sim side (with requirejs) or with wrapper code (just a global, see WrapperUtils.js).

**Comment by pixelzoom** [comment]
What's the barrier to having a library that encapsulates tandem id and is usable by both sims and wrappers?

**Comment by pixelzoom** [comment]
Please continue the discussion about tandem id encapsulation in #41.

**Comment by samreid** [comment]
It seems best to discuss this as a development team to decide how to proceed.

**Comment by pixelzoom** [comment]
1/8/18 dev meeting notes:
`createRootTandem` and `createStaticTandem` not longer exist. Validation occurs when `addInstance` is called.
