### ISSUE TITLE
Anti-pattern for defining static readonly class properties. 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#278]
I'm seeing a pattern of definiting static class properties that is concerning. It results in those constants being writeable when they should be `readonly`.  

For example, here's Vector2.ts:

```typescript
export default class Vector2 implements TPoolable {
...
  public static ZERO: Vector2;
  public static X_UNIT: Vector2;
  public static Y_UNIT: Vector2
  public static Vector2IO: IOType;
}

Vector2.ZERO = assert ? new ImmutableVector2( 0, 0 ) : new Vector2( 0, 0 );
Vector2.X_UNIT = assert ? new ImmutableVector2( 1, 0 ) : new Vector2( 1, 0 );
Vector2.Y_UNIT = assert ? new ImmutableVector2( 0, 1 ) : new Vector2( 0, 1 );

Vector2.Vector2IO = new IOType<Vector2, Vector2StateObject>( 'Vector2IO', {
  ...
} );
```

All of the `static` properties should be `static readonly`. And they should be instantiated inside the `class` definition, not outside the class definition.  Like this:

```typescript
export default class Vector2 implements TPoolable {
...
  public static ZERO = assert ? new ImmutableVector2( 0, 0 ) : new Vector2( 0, 0 );
  public static X_UNIT = assert ? new ImmutableVector2( 1, 0 ) : new Vector2( 1, 0 );
  public static Y_UNIT = assert ? new ImmutableVector2( 0, 1 ) : new Vector2( 0, 1 );
  public static Vector2IO = new IOType<Vector2, Vector2StateObject>( 'Vector2IO', {
    ...
  } );
}
```

A couple of things for discussion at developer meeting:

(1) PSA and recommendation not to use this pattern. Statics that are read-only should have the `readonly` modifier.

(2) Can we write a lint rule to prevent this, and identify all of the existing cases?

**Comment by pixelzoom** [comment]
This problem is widespread.  For example, looking only at IOType definitions:

@samreid I see this anti-pattern throughout cck-common:

* CircuitElement.CircuitElementIO
* Resistor.ResistorIO
* Vertex.VertexIO

@jonathanolson in density-buoyancy-common and gravity-and-orbits:

* Cuboid.CuboidIO
* Gravity.GravityIO
* Mass.MassIO
* Material.MaterialIO
* Body.BodyIO

@jbphet in greenhouse-effect, you're instantiating these inside the class definition, but missing `readonly` modifier:

* public static EMEnergyPacketIO
* all `public static` in Photon.ts
* public static WaveCreationSpecIO 
* public static EMWaveSourceIO
* public static WaveIO

@marlitas in mean-share-and-balance:
* Pipe.PipeIO 

@jonathanolson in scenery:
* Input.InputIO
* Pointer.PointerIO

**Comment by jonathanolson** [comment]
Tried out the Vector2 example (since it was not ported that way because of ImmutableVector2), and it fails:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/480878/197419433-9785a3e1-5580-4cde-8e66-bda6adea422c.png">

I don't see a way of handling this with other ways easily, can you recommend a pattern for use at this site other than what's being done?

**Comment by jonathanolson** [comment]
Avoiding this pattern for most of the above cases however seems quite helpful.

**Comment by marlitas** [comment]
Addressed the MSaB occurrence. Unassigning.

**Comment by pixelzoom** [comment]
@marlitas Static constants should not be assigned in the constructor, because the constructor is called every time that `new Pipe` is called.   See the commit above for the correct way to define a static constant.  Let me know if you have any questions.

**Comment by samreid** [comment]
I agree these are antipatterns but also wanted to point out the overlap in https://github.com/phetsims/tandem/issues/275 in which we may (as a long term solution) combine IOTypes with the core types.

**Comment by pixelzoom** [comment]
Yes, there's indeed overlap with #275.  But I want to emphazied that, while the examples I've pointed to involve IOTypes, the antipattern applies to all statics, not just IOTypes.  Do a search for "public static" and you'll find many examples.

**Comment by jbphet** [comment]
Thanks for pointing this out @pixelzoom.  I made changes in quite a few places in greenhouse-effect, beyond the list shown above.  @marlitas - I agree that a lint rule for this would be helpful.

**Comment by jessegreenberg** [comment]
Here is the example AST, it should be easy to make a lint rule to flag when `readonly` is missing: https://typescript-eslint.io/play/#ts=4.8.4&sourceType=module&showAST=es&code=MYGwhgzhAECyCeBhcVoG8CwAoa0AOArgEYgCWw0EALmFedAE4CmYAJgPYB2I80AKgFEAynwD6fABIBJAHIBxaAF5oAckEiVAbmwBfIA

**Comment by samreid** [comment]
Dev meeting Nov 17 2022.

We agreed that making public static class properties `readonly` is best.  Just something that needs to be cleaned up.

@zepumph: I see 262 usages where this pattern is happening.  Maybe half of them can be fixed. So that is maybe 2 hours of work to do it all.
@AgustinVallejo: I'm happy to help on this.  
@kathy-phet: Can @pixelzoom and @AgustinVallejo pair together for a "kick-off" meeting, then @AgustinVallejo take it from there?

@pixelzoom & @AgustinVallejo: Great!

Here is a regex from @zepumph that may help `static .*:.*;`

**Comment by pixelzoom** [comment]
@AgustinVallejo and I met about this after today's dev meeting.  He'll use the regex `static .*:.*;` to identify potential places to add `readonly`.  For any that prove to be problematic (like Vector2), he'll note them, and he and I will review.

**Comment by pixelzoom** [comment]
Regex `static .*:.*;` is not identifying all cases.  We also need to check `static .*=.* (assignment) and `static .*:.*` (mulit-line).

**Comment by AgustinVallejo** [comment]
Here are some weird cases we found regarding this issue, we'll be looking into it.
- [ ]  Pose.ts ask CK and SR why private static
only static on Multilin assign to SR
- [x]  Create issue in CCKC, delete unused and assign to SR
- [ ]  BinPacker.ts - Bin
- [ ] Matrix3.ts
- [ ] Vector2.ts
- [ ] Vector3.ts
- [ ] Vector4
- [ ]  GAO - SceneFactory.ts, BodyRenderer.ts
- [ ]  Helper.ts
- [ ]  BANScreenView - protonsCreatorNodeModelCenter use modelViewTransform...
- [ ]  LighBulb.ts - vertexDelta use LightBulb.createSamplePoints
- [ ]  Resistor.ts
- [ ]  Mass.ts density boyancy common cannot change because it kills Cuboid.ts

**Comment by pixelzoom** [comment]
In the above commits, I addressed a bunch more cases.  There are still some cases that have not been addressed (as indicated in https://github.com/phetsims/tandem/issues/278#issuecomment-1334098347) because they are problematic.  And there are some cases in sun and scenery that are just a little too much work to untangle and test.  But I don't feel like we need to address _every_ case for this issue, and I feel like we're at a good stopping point.  @AgustinVallejo do you agree?  If so, feel free to close this issue. If not, what else should we do?
