### ISSUE TITLE
Eliminate createStaticTandem and always buffer tandems before listeners wired up

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#34]

**Comment by samreid** [comment]
implement above, @zepumph can you please review?

**Comment by samreid** [comment]
I also switched to a pattern where tandems are flushed as soon as the tandem listeners are added (rather than all instance listeners being added), instance listeners get a callback for all pre-existing tandems in the right order.  The effect should be the same but without the odd waiting period we had to support previously.

**Comment by zepumph** [comment]
>I also switched to a pattern where tandems are flushed as soon as the tandem listeners are added (rather than all instance listeners being added)

Does this have to do with launching Tandem in phetio.js rather than in simLauncher?

The practice look really good. It is nice when you see commits that simplify the code, and I think that the above do just that. I see 17 instances of `createStaticTandem`. Would you like to go for the switch, or should I?

**Comment by samreid** [comment]
We still need `createStaticTandem` but now it means (a) to create a global tandem without another tandem instance (instead of the old meaning which was to buffer it separately as well as (a)).

> Does this have to do with launching Tandem in phetio.js rather than in simLauncher?

`Tandem.launch` is called at the end of phetio.js, that indicates listeners are wired up and flushes the buffer.

**Comment by zepumph** [comment]
I'm sorry I don't understand, let's talk soon.

**Comment by zepumph** [comment]
@samreid and I spoke. We decided it would be good to delete `createStaticTandem`, and instead export a single rootTandem from Tandem, and use that at the call site, like:
```
  var tandem = Tandem.rootTandem.createTandem( 'utteranceQueue' );
```

After doing this, we should be able to simplify `tandemRequired/Optional` methods to utilize this; these singletons could be right on the static object, rather than functions.

@samreid or I will get to this, whoever has time first.

**Comment by samreid** [comment]
Fixed in preceding commits. @zepumph can you please review changes to Tandem.js and spot check a few usages?

**Comment by zepumph** [comment]
This looks really nice. Thanks! I have never noticed this before, but it seems weird to me that Tandem.js is reaching in to packageJSON for a rootTandem. At the very least perhaps it should fall back to something.  I'll create a new issue to discuss. Otherwise good to close!

**Comment by zepumph** [comment]
This is good to go. Closing
