### ISSUE TITLE
Should Tandem.js use package.JSON

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#35]
I noticed as part of  From https://github.com/phetsims/tandem/issues/34 that we use the package.JSON's name of a sim to get the root tandem. Is there a better way of doing this?

From https://github.com/phetsims/tandem/issues/34#issuecomment-345830142:
> I have never noticed this before, but it seems weird to me that Tandem.js is reaching in to packageJSON for a rootTandem. At the very least perhaps it should fall back to something. I'll create a new issue to discuss.

@samreid should Tandem know about package.json for the name of the root tandem? Maybe it would be better to have that passed in from joist/more sim specific code.

**Comment by samreid** [comment]
The root tandem must be available before sim modules are loaded so that "static" tandems will work.  So we cannot, for example, pass a variable from `sim-main.js`.  That leaves us with something that can be loaded in tandem/ by a module or a preload constant.  Loading from package.json is the former, I'm not sure what other good options we have.  Suggestions?

**Comment by zepumph** [comment]
Not good suggestions. Brainstorming. We could batch everything before tandem is launched, and when launched tack on the "root" to the front of all of the ids in the batched list before draining/addInstance, then from there rootTandem would be defined as usual.

**Comment by samreid** [comment]
That would work, but is there a good reason not to use the name from package.json?  Wouldn't adding the same name somewhere else be an undesirable duplication?

**Comment by zepumph** [comment]
Makes sense and agreed. Closing
