### ISSUE TITLE
Review IOObject.js

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#36]
From https://github.com/phetsims/tandem/issues/31 @zepumph and I implemented a new type called IOObject.js which is intended to be used as a base type for instrumented PhET-iO types.  It attempts to standardize a number of new options that were being handled with an odd strategy in phet-io.js.

IOObject.js is checked in to master for review, and we have purposefully avoided using it until review is complete.

Here's a visual diff of how it would be used, for instance, in PrecipitateParticle.js (assuming that SoluteParticle.js inherited from IOObject).

![image](https://user-images.githubusercontent.com/679486/33225261-446f2c8e-d131-11e7-8e7a-21a5ae8e339a.png)

Please note in particular:
* this pattern uses `tandem` in the options
* automatically takes care of `tandem.addInstance`
* automatically takes care of `tandem.removeInstance` in the inherited `dispose` call
* the `phetioType` is passed as an option
* this will prevent us from needing to put `this.{{SUBTYPE_NAME}}Tandem = tandem` anywhere
* this will allow us to eliminate `createSupertypeTandem`
* We will be able to eliminate the PhET-iO options from the top of phetio.js

The two TODOs marked in IOObject can be investigated once this preliminary review is complete.

Discussion about whether this should be a base type or mixin are archived here--my recommendation is base type: https://github.com/phetsims/tandem/issues/31#issuecomment-346749272

@pixelzoom can you please take look?

**Comment by pixelzoom** [comment]
The `PrecipitateParticle` example isn't helping me - I'm guessing that the diff is clipped in important places.  I would also help to see `SoluteParticle`.  @samreid can you please add a comment with the proposed implementations of `PrecipitateParticle` and `SoluteParticle`?

**Comment by samreid** [comment]
> the diff is clipped in important places

Yes, I used the IDEA diff "accordion" that only shows changes (rightmost icon in this pic)
![image](https://user-images.githubusercontent.com/679486/33332961-dee3d8e8-d422-11e7-874a-d22bd0dd104b.png)

I'll prepare a text example for review.

**Comment by samreid** [comment]
I'm hitting a snag that IOObject.addInstance is being called before the sub constructor is complete.  This means we cannot do `toStateObject` at this point.  So we will have to abandon state snapshots or find a way to make IOObject.addInstance go at the end of construction.

@zepumph can we chat about which way to go?

**Comment by samreid** [comment]
Branch is here: https://github.com/phetsims/beers-law-lab/issues/219

It will reproduce the problem from my previous comment--use instance proxies, then shake solute, then evaporate.  When PrecipitateParticle is created it will fail out.

**Comment by samreid** [comment]
I discussed it with @zepumph and we decided to add `PhETIO.js.getStateForObject` and change instance proxies to read like so:
```js
      var instanceAdded = function( phetioID, type, options ) {

        simIFrameClient.invoke('phetio','getStateForObject',[phetioID],function(stateObject){
          assert && assert( type, 'type should be defined' );
          instances[ phetioID ] = window.createInstanceProxyDiv( phetioID, type, isType, window.simIFrameClient, stateObject, options );
          instances[ phetioID ].phetioID = phetioID;
          updateControlPanel();
          filterAndAppend( phetioID );
        });
      };
```
Then we will eliminate the initial `stateObject` from the instanceAdded emits.

**Comment by zepumph** [comment]
@samreid I've been working on this for a while and I have hit an impasse. There is quite a bit of issue downstream of the async call above. Imagine this chain of events:

1. addInstance emitted
2. in instance proxies send out for the 'getStateForObject' method.
3. async in the other frame the instance is deleted.
4. the instanceRemovedListener fires and tries to delete something from the instance proxies wrapper that hasn't even been created yet. 

This error has been quite hard for me to trace, because of its async nature. I'm getting the same error for the `getStateForObject` method where the object has already been deleted before we can get the "initial" state for it. 

I'll keep working to see if I can hack out no-ops for these edge cases.

**Comment by zepumph** [comment]
@samreid I think the above is pretty safe. Basically we removed the assertion that for an instance to be removed, it must exist in instance proxies, which is understandable because we added a race condition in if an instance is removed in the sim before instance proxies can get the initial state (also async call) and create the div UI component. Please review the changes above.

**Comment by samreid** [comment]
I'm seeing a few problems with the proposed solution. First, testing it on beer's law lab, particles are not disposed when they hit the solution (it should go back down to 211 instances, but the created shaker particles never go away).  Second, it seems that `null` would be better than `{}` for a non-existent `phetioid`. Or maybe even an error.

**Comment by samreid** [comment]
I wonder if the remove is getting called before the add callback completes--this could explain why we are getting zombies.

**Comment by samreid** [comment]
Perhaps the divs are being removed but the count in the control panel isn't updating.

**Comment by samreid** [comment]
Fixed in preceding commit.

**Comment by samreid** [comment]
In the "ioobject" branch of beers-law-lab, I applied the IOObject base class to all types that were using `tandem.addInstance`.  It is now ready for @pixelzoom to review.  Steps for review:

0. Pull all in master, checkout the beers-law-lab `ioobject` branch and pull it too.
1. Read through tandem/js/IOObject.js
2. Compare beers-law-lab master to beers-law-lab ioobject.  Begin with `ShakerParticle.js`--it shows how a subclass of IOObject would look.  Note the `tandem` is now passed through options, along with the `phetioType`.  There is no need to call `addInstance` or `removeInstance` in the IOObject subtype because it is handled automatically in the parent.  Other notes on this pattern are given in https://github.com/phetsims/tandem/issues/36#issue-276709221
3. Review the rest of the changes between beers-law-lab master to ioobject branch.
4. Note I added line breaks in ConcentrationModel.js where the code was particularly dense.
5. During instrumentation I "lost" 2 instrumented objects.  That is to say, before I started there were 211 instrumented instances, and afterwards there are only 209.  It's up to me to find out which are missing and if they are important, but this shouldn't prohibit your review.
6. For each of the options that begin with the `phetio` prefix in `IOObject.js` search for at least one usage to see how they are used in practice.

Note there are 2 TODOs in IOObject.js.  Those do not need to be resolved before the review or as part of the review, @zepumph and I will take care of them if IOObject passes review.

IOObject is a bottleneck for several PhET-iO issues, so we recommend it to be as high a priority as @pixelzoom and @ariel-phet can tolerate given other workloads.

**Comment by zepumph** [comment]
@pixelzoom correct me if I am wrong about the closing.

**Comment by pixelzoom** [comment]
Thanks, I accidentally closed this - I'm actually in the middle of reviewing it.

**Comment by pixelzoom** [comment]
After completing step (1), review IOObject:

IOObject and ObjectIO in the same file, potentially confusing:

```js
13 var ObjectIO = require( 'ifphetio!PHET_IO/types/ObjectIO' );
26 phetioType: ObjectIO,    // Supply the appropriate IO type
```

I don’t understand this comment, looks like a grammatical error:

```js
28 phetioEvents: true,      // To permit into the phet-io events stream
```


Name does not match the convention for tandem instance fields. This should be named `this.ioObjectTandem`:

```js
36 this.phetObjectTandem = options.tandem;
```

Line 58 is exceptionally long, exceeds the line limit for PhET style.

No safeguards that prevents calling `endEvent` before `startEvent`, calling `startEvent` or `endEvent` multiple times, etc.  This is not robust.

No visibility annotations for any of the instance methods.

**Comment by pixelzoom** [comment]
> Begin with ShakerParticle.js--it shows how a subclass of IOObject would look

ShakerParticle is not a subtype of IOObject. Presumably you mean SoluteParticle?

**Comment by pixelzoom** [comment]
Steps (2) and (3), rest of the changes in "ioobject" branch:

- [ ] `tandem: Tandem.required` should presumably be defined in supertype SoluteParticle, not duplicated in both subtypes (ShakerParticle, PrecipitateParticle)

- [ ] `tandem: Tandem.required` is presumably not needed in Shaker, since it's already specified in supertype Movable.

- [ ] PrecipitateParticle presumably does not need to specify `phetioState: true` since the default is `true`.

- [ ] Why was this assertion added to PrecipitateParticle? If is redundant since `solute` is used prior to this.  And there's nothing similar in ShakerParticle, the other subtype of SoluteParticle.
`37 assert && assert( !!solute, 'solute should exist' );`

Noted, but probably unrelated to this issue and likely to need addressing in master:

- [ ] Documentation error in SoluteParticle, this belongs in PrecipitateParticle, same error in master?
`45 documentation: 'A particle that shows at the bottom of a saturated solution.'`

- [ ] Document why this is needed in Solute, add visibility annotation:
`71 this.tandemName = options.tandem.tail;`

**Comment by pixelzoom** [comment]
@samreid said:
>  I applied the IOObject base class to all types that were using tandem.addInstance

To clarify... It looks like you applied this mostly (solely?) to view types.  View types (subtypes of scenery nodes) continue to use the old approach.  Correct?

**Comment by pixelzoom** [comment]
Step (6), for each of the options that begin with the phetio prefix in IOObject.js search for at least one usage to see how they are used in practice:

- [ ] Why are BeersLawSolution, PrecipitateParticle and Solute specifying `phetState: true`? That is the default in IOObject.

- [ ] Could not complete this step because there are no usages of `phetioEvents`, `phetioReadOnly ` and `phetioInstanceDocumentation`.

**Comment by pixelzoom** [comment]
Overall:

• Lots of specific questions (see checklist items in above comments), but I'm guessing that the majority of these are instrumentation errors, and not specific to IOObject.

• In it's current state, IOObject is not ready for production.  See https://github.com/phetsims/tandem/issues/36#issuecomment-349109911.

• I like passing tandem via options, rather than as a required constructor parameter. But that's not really specific to this approach, it could be passed via options in the previous approach.

• Not having to call `addInstance` or `removeInstance` is certainly convenient.  

• It looks like the primary "win" is to consolidate definition of `startEvent` and `endEvent` - which are not at all robust, see https://github.com/phetsims/tandem/issues/36#issuecomment-349109911.

• Extending IOObject seems reasonable in the model.  But you should get @jonathanolson's input on implications for the view (scenery) side. Ideally, we should be using the same approach for model and view. 

Review completed.

**Comment by samreid** [comment]
> ShakerParticle is not a subtype of IOObject. Presumably you mean SoluteParticle?

ShakerParticle extends SoluteParticle which extends IOObject

**Comment by pixelzoom** [comment]
Got it, and (as indicated above) ShakerParticle - SoluteParticle - IOObject hierarchy has been reviewed.

**Comment by samreid** [comment]
Responding to feedback in https://github.com/phetsims/tandem/issues/36#issuecomment-349109911

> IOObject and ObjectIO in the same file, potentially confusing.

A Type always refers to its IO Type (formerly known as TType).  For instance Vector2 refers to Vector2IO.  IOObject has the IO prefix because it is specific to PhET-iO.  Not sure how to clarify this.

> I don’t understand this comment, looks like a grammatical error:

I updated the options docs in preceding commit

> Name does not match the convention for tandem instance fields. 

Fixed in a commit

> Line 58 is exceptionally long, exceeds the line limit for PhET style.

I shortened it a bit (still over limit but IMO best readability this way).

> No safeguards that prevents calling endEvent before startEvent, calling startEvent or endEvent multiple times, etc. This is not robust.

The safeguards are in phetioEvents.js.  Sending an end with no start will cause an error.  Sending a start with no end is currently not catchable.  But we could add a check for unclosed events at the end of each frame if it would be worth the effort.

**Comment by samreid** [comment]
Responding to feedback from https://github.com/phetsims/tandem/issues/36#issuecomment-349118684

> tandem: Tandem.required should presumably be defined in supertype SoluteParticle, not duplicated in both subtypes (ShakerParticle, PrecipitateParticle)

Fixed in preceding commit.

> tandem: Tandem.required is presumably not needed in Shaker, since the default in supertype Movable is tandem: Tandem.required.

Removed in preceding commit.

> PrecipitateParticle presumably does not need to specify phetioState: true, since the default in IOObject is phetioState: true.

Fixed in preceding commit.  But this may be a sticky issue because I don't know whether @zepumph and I are decided whether things like state and events should be opt-in or opt-out.

> Why was this assertion added to PrecipitateParticle? 

Removed extraneous assertion in preceding commit.

**Comment by samreid** [comment]
> To clarify... It looks like you applied this mostly (solely?) to view types. View types (subtypes of scenery nodes) continue to use the old approach.

Yes, scenery currently has an incompatible implementation of PhET-iO support, but the APIs are being designed to match up.  For instance, the IOObject options match the Node options.

**Comment by samreid** [comment]
> Why are BeersLawSolution, PrecipitateParticle and Solute specifying phetState: true? That is the default in IOObject.

The main reason is that @zepumph and I have been hedging our bets about whether things should be "opt-in" or "opt-out".  Perhaps types should be opt-in to being instrumented, but once instrumented should be "opt-out" from specific features?  I'll remove the phetioState: true annotations in case we continue in that direction.

**Comment by samreid** [comment]
> Could not complete this step because there are no usages of phetioEvents, phetioReadOnly and phetioInstanceDocumentation.

For this part of the review, please search across all repos.

**Comment by samreid** [comment]
> Extending IOObject seems reasonable in the model. But you should get @jonathanolson's input on implications for the view (scenery) side. Ideally, we should be using the same approach for model and view.

@jonathanolson recommends making IOObject a mixin.  However, in https://github.com/phetsims/tandem/issues/31#issuecomment-346749272 I reasoned that a base class would be more appropriate.  It seems it would be possible to change Node's parent class from Object to IOObject, then delete all of the PhET-iO support from Node.js (since it would be handled by the parent class).

**Comment by samreid** [comment]
@pixelzoom thanks for the careful review.  As part of addressing and responding to your feedback, I purposefully left checkboxes (like the ones in https://github.com/phetsims/tandem/issues/36#issuecomment-349109911 ) unchecked since I wasn't sure that my proposed commits would be satisfactory--you can use those checkboxes to track progress if you wish.

**Comment by pixelzoom** [comment]
Regarding these related checklist items and @samreid's replies:

> > - [ ] PrecipitateParticle presumably does not need to specify phetioState: true, since the default in IOObject is phetioState: true.
>
> Fixed in preceding commit. But this may be a sticky issue because I don't know whether @zepumph and I are decided whether things like state and events should be opt-in or opt-out.
>
> > - [ ] Why are BeersLawSolution, PrecipitateParticle and Solute specifying phetState: true? That is the default in IOObject.
>
> The main reason is that @zepumph and I have been hedging our bets about whether things should be "opt-in" or "opt-out". Perhaps types should be opt-in to being instrumented, but once instrumented should be "opt-out" from specific features? I'll remove the phetioState: true annotations in case we continue in that direction.

I understand that opt-in vs opt-out may still be  undecided. But if you're going to "hedge bets", then you should do so everywhere, not in a few seemingly random places.  Since the implementation of IOObject currently defaults to `phetState: true` (opt-out), and hedging has not been done uniformly, it makes sense to remove these. (Which you did.)

**Comment by pixelzoom** [comment]
Re this item and @samreid's reply:

> > Could not complete this step because there are no usages of `phetioEvents`, `phetioReadOnly` and `phetioInstanceDocumentation`.
>
> For this part of the review, please search across all repos.

Done.

**Comment by pixelzoom** [comment]
Re: 

> > To clarify... It looks like you applied this mostly (solely?) to view types. View types (subtypes of scenery nodes) continue to use the old approach.
> 
> Yes, scenery currently has an incompatible implementation of PhET-iO support, but the APIs are being designed to match up.  For instance, the IOObject options match the Node options.

Then why not use IOObject in scenery? Or factor out the options to be used in both IOObject and Node? The need to keep Node and IOObject options in-sync creates a longterm maintenance issue.

**Comment by pixelzoom** [comment]
Re:

>> - [ ] No safeguards that prevents calling endEvent before startEvent, calling startEvent or endEvent multiple times, etc. This is not robust.
> The safeguards are in phetioEvents.js. Sending an end with no start will cause an error. Sending a start with no end is currently not catchable. But we could add a check for unclosed events at the end of each frame if it would be worth the effort.

I don't believe that sending a start with no ends in not catchable. If so, then you have a software design problem.  You should also be able to catch 2 starts, 2 ends, and other invalid cases. This should be an easy problem to solve with a flag or counter.

**Comment by pixelzoom** [comment]
@samreid I've moved unresolved sub-issues to their own GitHub issues.  Feel free to close this if you feel that the IOObject review is completed.

**Comment by samreid** [comment]
Thanks for the review @pixelzoom, closing.
