### ISSUE TITLE
buggy Tandem.isLegalAndUsable

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#37]
Tandem.js line 249:

`return this.supplied || (this.optional && !this.supplied);`

Tandem instances do not have an `optional` field.  Tandem does have a static `optional` field.

**Comment by zepumph** [comment]
Wow this is a big one! Quite a while ago we name changed from "optional" to "required" and must have missed this usage. There will probably be quite a few assertions that trigger from this.

**Comment by zepumph** [comment]
@samreid I think that we have been thinking about this method wrong. The `isLegalAndUsable` check really, when it boils down to it is just the `supplied` check, because even if the instance is tandemOptional, if it isn't supplied, then you shouldn't be calling phetioEvents or other phetio features on this. For example, see this assertion in Property.js:
```js
    // When running as phet-io, if the tandem is specified, the type must be specified.
    // This assertion helps in instrumenting code that has the tandem but not type
    Tandem.validationEnabled() && options.tandem.isLegalAndUsable() && assert && assert( !!options.phetioType,
      'Value type passed to Property must be specified. Tandem.id: ' + options.tandem.id );
```

Here we want tandem.isLegalAndUsable() to fail for an optional tandem.

My proposed solution ends up being basically business as usual. Since for the last many months, `this.optional` has been undefined, `tandem.isLegalAndUsable()` is mapping directly to `this.supplied`. I think that is correct. A tandem is not usable if it is not supplied, even if it is optional.

```js

    isLegalAndUsable: function() {

      // If we are not in phet-io mode, then the tandem is not legal and usable.
      if ( !PHET_IO_ENABLED ) {
        return false;
      }

      // A tandem is legal if it has been supplied. Additionally unsupplied are acceptable if it is an optional tandem.
      return this.supplied;
    }
```

**Comment by pixelzoom** [comment]
`isLegalAndUsable` is certainly confusing, and not well-documented.  `isSuppliedOrOptional` would have been a better name, rather than introducing the poorly defined "legal" and "usable".

**Comment by zepumph** [comment]
I this it is more like `phetioEnabledAndIsSupplied`. That's where the legal/usable came from.

**Comment by samreid** [comment]
I went with 

```js
    /**
     * Return true if this tandem is supplied and the sim is running in PhET-iO mode.
     * @returns {boolean}
     * @public
     */
    isSuppliedAndEnabled: function() {
      return this.supplied && PHET_IO_ENABLED;
    }
```

@pixelzoom does this seem good to you?
