### ISSUE TITLE
tandem id separator is duplicated as a string literal

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#40]
I see `'.'` duplicated 6 times.  The tandem id separator should most definitely be factored out into a constant.  And made public via a static constant if you're using it outside of Tandem.

**Comment by pixelzoom** [comment]
And the separator is indeed used in multiple places outside of Tandem, where it appears as a literal.   Numerous examples in the phet-io and phet-io-wrapper-* repositories. 

E.g. in sonificationUISoundsSampled.js

`163  var lastIdElement = messageObject.phetioID.split('.').pop();`

**Comment by zepumph** [comment]
With `PhetIOIDUtils.js`, this has been taken care of in Tandem, but there are many other usages like in phet-io:
![image](https://user-images.githubusercontent.com/6856943/37538584-e9006426-2905-11e8-9831-83cd41123bb8.png)

I'm not as worried about it in the Sonification wrapper, since those are attached to specific publications of sims, and the wrappers themselves aren't on a long term maintainability track.

**Comment by zepumph** [comment]
I did work on this, and eliminated all usages of the hard coded separator in the sim code. I also set up the classroom activity and lab book wrapper to accept `PhetioIDUtils.js` calls in requirejs mode (it already worked when built). I fixed some of the sonification wrapper's usages, assuring that PhetioIDUtils works in requirejs and built version of the wrapper, but I'm still not convinced that it is worth breaking up lines like `      simIFrameClient.invoke( 'buildAnAtom.' + screen + '.model.particleAtom.protonCountProperty', 'link', [ function( linkedProtonCount ) {` To use `PhetioIDUtils`.

I think we are ready to close this issue, because to me the sonification wrapper is client code pointing to published sims, using actual id's instead of calling on the separators. Similarly, we don't want to change ids like the following in classroom-activity's `forces-and-motion-basics.js`
```
 customization: {
      predict: [
        // Hide checkbox panel, volume control, and reset all button
        { phetioID: 'forcesAndMotionBasics.netForceScreen.view.controlPanel', method: 'setVisible', args: [ false ] },
        // Hide Return button
        { phetioID: 'forcesAndMotionBasics.netForceScreen.view.returnButton', method: 'setVisible', args: [ false ] },
        // Hide left force arrow
        { phetioID: 'forcesAndMotionBasics.netForceScreen.view.leftArrow', method: 'setVisible', args: [ false ] },
        // Hide right force arrow
        { phetioID: 'forcesAndMotionBasics.netForceScreen.view.rightArrow', method: 'setVisible', args: [ false ] },
        // Disable the sim
        { phetioID: 'forcesAndMotionBasics.activeProperty', method: 'setValue', args: [ false ] },
        // Set Blue puller knot property (puller position is linked)
        { phetioID: 'forcesAndMotionBasics.netForceScreen.model.mediumBluePuller.knotProperty', method: 'setValue', args: [ 'forcesAndMotionBasics.netForceScreen.model.blueKnot2' ] },
        // Set Red puller knot property (puller position is linked)
        { phetioID: 'forcesAndMotionBasics.netForceScreen.model.largeRedPuller.knotProperty', method: 'setValue', args: [ 'forcesAndMotionBasics.netForceScreen.model.redKnot1' ] },
        // Hide Go button
        { phetioID: 'forcesAndMotionBasics.netForceScreen.view.goPauseButton', method: 'setVisible', args: [ false ] }
      ],
```

What do you think @samreid @pixelzoom.

**Comment by samreid** [comment]
Right, we agreed that complete phetioIDs like `'forcesAndMotionBasics.netForceScreen.view.controlPanel'` would remain as they are, without having the `'.'` factored out.

**Comment by zepumph** [comment]
Glad we agree. Thanks all! Closing
