### ISSUE TITLE
Tandem: addInstance and removeInstance lack safeguards

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#42]
I see no safeguards in Tandem that prevent the same instance from being added/removed twice, or for removing an instance that hadn't been added. 

Here's an example, where nothing fails with assertions enabled:

```
> var lengthTandem = new phet.tandem.Tandem( 'lengthProperty' )
> var widthTandem = new phet.tandem.Tandem( 'widthProperty' )
> var lengthProperty = new phet.axon.Property( 0 )
> var widthProperty = new phet.axon.Property( 0 )

> lengthTandem.addInstance( lengthProperty )

// should fail
> lengthTandem.addInstance( lengthProperty )

> lengthTandem.removeInstance( lengthProperty )

// should fail
> lengthTandem.removeInstance( lengthProperty )

// should fail
lengthTandem.removeInstance( widthProperty )
```

**Comment by zepumph** [comment]
Tandem does not have this logic, you are right. We wrote Tandem as a thin layer of string/id manipulation, but for the most part it isn't that powerful. Instead we have safeguards in place in the addInstance listener in phetio.js. `phetio.addInstance()` is the method that get's called whenever `Tandem`'s addInstance is called (sorta confusing sorry), think of this as the meat and bones of tandem registration. Here there are the safeguards you are talking about. See phetio.js:576:
```
        assert && assert( phetioObject === instanceMap[ phetioID ].instance, 'Cannot register two different instances to the same id: ' + phetioID );

```
 

For more safeguards dealing with phetio's implementation using Tandem see `PhetioObject.initializePhetioObject`.

I personally feel like there is nothing more needed right now with Tandem, since we don't use `add/removeInstance` in the way demonstrated above (without the phetio listener wired in). Tagging @samreid to see if he feels differently.

@pixelzoom is the above enough explanation on where the safeguards are?

**Comment by samreid** [comment]
![image](https://user-images.githubusercontent.com/679486/43901008-9b7f005c-9ba3-11e8-844c-eef56b44b12d.png)

Closing.
