### ISSUE TITLE
Should PhetioObject allow Property link loops?

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#57]
When developing PhetioObject, we disallowed cycles in Property links.  That is, one Property cannot (by links to other properties) cascade a change to itself.  The reasoning was (a) this would be faster and less memory invasive for PhetioObject allocations and (b) Property cycles probably indicate a flaw in the design of the Property links.

As we rolled out PhetioObject, we found a few places where it was trivial to eliminate a Property loop.  However, in Hooke's Law there was a Property loop which I could not easily eliminate, see https://github.com/phetsims/hookes-law/issues/52.  @pixelzoom is going to investigate the Property loop and ironing it out in Hooke's Law, but this raised the question for me about whether this functionality belongs here.

If we want to detect and eliminate Property loops, that seems like something that should be done in axon, not tandem.  And perhaps it is OK to create an extra `[]` in each PhetioObject, which is all that is needed to add support for loops.

It seems unlikely that we would want the Property loop in the "stable API data stream".  However, it seems like a very large burden if during simulation instrumentation we must eliminate all Property loops.

**Comment by samreid** [comment]
In the preceding commit, I added support for Property loops.  We may still decide to revert this based on discussion here and in https://github.com/phetsims/hookes-law/issues/52

**Comment by zepumph** [comment]
The commit looks good. I wonder if we want to make this an option, and assert out for most cases saying "you probably don't want property event looping." Then if you can't code around it in the implementation (like for HL), then you can add an option to a specific Property instance like `options.allowEventLooping = true`.

I'm trying to balance flexibility vs. the complexity of PhET-iO and the number of "gotcha's." Tagging @pixelzoom because he was involved in this specific case for HL, and may be able to speak to how often you would want a property to loop in the event stream.

**Comment by pixelzoom** [comment]
Yes, it would be nice to turn it on an off.  @samreid also proposed (somewhere, perhaps in a Slack conversation) that detecting Property loops should be the responsibility of axon, rather than phet-io.

**Comment by pixelzoom** [comment]
If we wanted to detect loops in axon, the place to handle it would probably be in `Property` `_notifyListeners`.   Bracket the call to `changeEmitter.emit2` with a `@private` flag.  Fail an assertion conditionally based on a query parameter, since this is likely to affect lots of existing code.   

Here's what `_notifyListeners` might look like: 

```js
      // @private
      _notifyListeners: function( oldValue ) {

        // We must short circuit based on tandem here as a guard against the toStateObject calls
        this.tandem.isSuppliedAndEnabled() && this.startEvent( 'model', 'changed', {
          oldValue: this.phetioType.elementType.toStateObject( oldValue ),
          newValue: this.phetioType.elementType.toStateObject( this.get() ),
          units: this.phetioType && this.phetioType.units
        }, this.changeEventOptions );

        assert && assert( !this.notifying || !phet.chipper.queryParameters.detectPropertyLoops, 
          'Property loop detected' );
        this.notifying = true;
        this.changedEmitter.emit2( this.get(), oldValue );
        this.notifying = false;

        this.tandem.isSuppliedAndEnabled() && this.endEvent();
      },
````

**Comment by pixelzoom** [comment]
I moved the detection of Property loops to https://github.com/phetsims/axon/issues/179.

**Comment by zepumph** [comment]
@samreid, in 89d81c69a40472b91e7a140d09ef8ab30a70a456 you removed an assertion that has caused tandem unit tests to fail for a few days. Do you think we should add that back in?

**Comment by samreid** [comment]
I updated the PhetioObjectTests in the preceding commit.  This issue is complete and we will continue in  phetsims/axon#179.
