### ISSUE TITLE
What "classes" should PhetioObject support?  How should we support them?

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#67]
As part of https://github.com/phetsims/axon/issues/184 @zepumph and I discussed phetioClasses for PhetioObject, which could look like this:

```js
    this.frameEndedEmitter = new Emitter( {
      tandem: ROOT_TANDEM.createTandem( 'frameEndedEmitter' ),
      phetioType: EmitterIO( [ { name: 'dt', type: NumberIO } ] ),
      phetioClasses: [ 'high-frequency', 'input-event' ]
    } );
```

This would give us a new paradigm for indicating classes like 'high-frequency' and 'input-event' and we could add classes like 'significant-model-event'.  How should we approach this?  Is it better to have an array of strings, or explicitly enumerated fields (like `phetioHighFrequency`)?  How do we determine which are the defaults and how do wrappers opt in or out of certain classes?

Does running a sim with a class disable mean it dosen't show up at all in wrappers?  If so, how can we make sure everything shows up in studio?  Would it just "opt in" to everything?

**Comment by zepumph** [comment]
This could potentially change the public api dramatically, marking as blocking thoughtful api release for FL.

**Comment by zepumph** [comment]
1. One key discussion point is if this system will be "opt-in" or "opt-out" based. It makes sense to me from an implementation standpoint that everything would be included by default and you could then omit items one by one. But this adds a level of complexity to the wrapper suite, because we would need to define the wrapper "class level". Colorized log will likely not want "high frequency" events.
2. What does "opt-out" mean? Would be uninstrument items entirely, or come up with new logic to keep opted out things out of the places we decide (event stream, studio???)
3. Could these classes be used to help organize studio, i.e 'important-model-properties' class could go at the top of the studio list.
3. Could more complicated sims create their own classes to help organize themselves?

**Comment by samreid** [comment]
In https://github.com/phetsims/phet-io/issues/1382#issuecomment-428677148 we discussed the need to be able to filter/subdivide events.  For example, validatePointers and voltageChanged are both "high frequency".  You get both or neither, but there is no way to select one.

**Comment by samreid** [comment]
We decided to add a new class `phetioPlaybackEvent` for events that are required for playback.  At the moment, this includes `frameEndedEmitter` and `validatePointersEmitter`.
